#!/bin/sh

# Universal Script Installer
# Copyright (c) 2015, Federico Damián Schonborn <github.feskyde>
# All rights reserved.

# script-skeleton (https://github.com/feskyde/script-skeleton)

## set script info

NAME="usi"
DESCRIPTION="A script for installing scripts, basically."
COMMAND="INSTALLER"

DATE="2015.10.22"
RELEASE="DBR"
CODENAME="Allegro"

COPYRIGHT="Copyright 2015, Federico Damián. All rights reserved."
LICENSE="BSD 3-Clause"

# USI information

ISCRIPT_NAME="GitUp"
ISCRIPT_FILE="gitup"
ISCRIPT_PATH=/usr/bin/

### options
### ISSUES: you need to put an "\n" (or the $NLINE variable) on every new line

OPTIONS_HEADER="\nList of options:"
OPTIONS_LIST="
\nOptional:
\n
\nuninstall: uninstalls the script
\ncheck: checks if script is installed"

## prints the help section

print_help() {
echo -e ""$NLINE""$BOLD"Usage: "$COMMAND""$COLEND""$NLINE""$OPTIONS_HEADER""$NLINE""$OPTIONS_LIST""$NLINE""
}

## prints the about section

print_about() {
echo -e "
"$BOLD""$NAME" version "$DATE" "$RELEASE" \"$CODENAME\".
"$DESCRIPTION"
"$COPYRIGHT"
"$NAME" is released under the "$LICENSE" license."$COLEND"
"
}

# set message prompt settings

ERROR="\e[31;1m"
DONE="\e[32;1m"
BOLD="\e[1m"
COLEND="\e[0m"
NLINE="\n"

# post-runtime functions

## prints the 'Done! message'

print_done() {
	echo -e ""$NLINE""$DONE"Done!"$COLEND""$NLINE""
}

# pre-runtime checks

check_root() {
	if [ ! $(whoami) = root ]
	then
		echo -e ""$NLINE""$ERROR"ERROR:"$COLEND""
		echo -e ""$BOLD"You are not root. "$ISCRIPT_NAME" will not be installed."$COLEND""$NLINE""
		exit
	fi
}

# runtime checks

check_installed() {
	if [ -f "$ISCRIPT_PATH""$ISCRIPT_FILE" ]
	then
		echo -e ""$NLINE""$DONE""$ISCRIPT_NAME" is installed!"$COLEND""$NLINE""
		exit
	else
		echo -e ""$NLINE""$ERROR""$ISCRIPT_NAME" is NOT installed!"$COLEND""$NLINE""
		exit
	fi
}

# start of case (options)

case $1 in
	"about") print_about;;
	"help")	print_help;;
	"")
		check_root
		echo -e ""$NLINE""$BOLD"Installing..."$COLEND""; cp "$ISCRIPT_FILE" "$ISCRIPT_PATH""$ISCRIPT_FILE"
		print_done
		;;
	"uninstall")
		check_root
		echo -e ""$NLINE""$BOLD"Uninstalling..."$COLEND""; rm -rf "$ISCRIPT_PATH""$ISCRIPT_FILE"
		print_done
		;;
	"check")
		check_root
		echo -e ""$NLINE""$BOLD"Checking for "$ISCRIPT_NAME"..."$COLEND""; check_installed
		print_done
		;;
esac

# end of script
