#!/bin/sh

# Git Uploader - INSTALLER

if [ ! $(whoami) = root ];then
	echo -e ""
	echo -e "\e[31;1mERROR:\e[0m"
	echo -e "\e[1mYou cannot install Git Uploader."
	echo -e "Check if you are the root user.\e[0m"
	echo -e "\e[31;1mERROR CODE: 0\e[0m"
	echo -e ""
	exit
else
	echo -e "\e[1m"
	echo -e "Installing..."
	echo -e "\e[0m"
	cp gitup /usr/bin/
	cp /functions/gitup.funcs /etc/gitup/gitup.funcs
	echo -e "\e[1m"
	echo -e "Done!"
	echo -e "\e[0m"
fi
